export default {

    "arboretum_heron_ruins": {
        location: "Washington Park Aboretum",
        title: "heron in ruins",
        description: `
            A great blue heron adorns the ruins of past civilization.
        `,
        time: "2024-12-28T14:28:25",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 320,
        exposure: "1/60 sec",
        stack: false,
        teleconverter: 1.4,
        flash: false,
    },

    "arboretum_raccoon_tree": {
        location: "Washington Park Aboretum",
        title: "raccoon",
        description: `
        `,
        time: "2025-04-26T08:06:36",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 12800,
        exposure: "1/800 sec",
        stack: false,
        teleconverter: "1.4x",
        flash: false,
    },

    "arizona_white_pocket_star_trails_20260318": {
        location: "Vermillion Cliffs, Arizona",
        title: "White Pocket Star Trails",
        description: `
        `,
        time: "2026-03-18T22:31:30",
        lens: "Fujifilm GF 45mm f/2.8 R WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/2.8",
        iso: 800,
        exposure: "8 min",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "arizona_wukoki_pueblo_20260316": {
        location: "Wupatki National Monument, Arizona",
        title: "Wukoki Pueblo",
        description: `
        `,
        time: "2026-03-16T14:20:05",
        lens: "Fujifilm GF 45mm f/2.8 R WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/5",
        iso: 80,
        exposure: "1/640 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "baker_moonlight_baker_20250812": {
        location: "Kulshan",
        title: "moonlight baker",
        description: `
        `,
        time: "2025-08-12T23:32:59",
        lens: "Fujifilm GF 45mm f/2.8 R WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 1600,
        exposure: "10 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "bradner_hoverfly_inflight": {
        location: "Bradner Gardens",
        title: "hoverfly in flight",
        description: `
        `,
        time: "2024-05-14T17:47:57",
        lens: "Laowa 85mm f/5.6 2x Ultra Macro APO",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 200,
        exposure: "1/200 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "brooks_vashti_sphinx_moth_20260612": {
        location: "Brooks Memorial State Park",
        title: "vashti sphinx moth",
        description: ``,
        time: "2026-06-12T23:48:25",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/10",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "clark_creek_blue_dasher_female_stack": {
        location: "Clark Lake",
        title: "blue dasher female",
        description: `
            <i>pachydiplax longipennis</i>
        `,
        time: "2025-06-15T13:09:37",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 100,
        exposure: "1/125 sec",
        stack: 2,
        teleconverter: false,
        flash: true,
    },
    
    "cougar_autumn_meadowhawk_meal": {
        location: "Cougar Mountain Regional Wildland Park",
        title: "autumn meadowhawk at mealtime",
        description: `
            An autumn meadowhawk (<i>sympetrum vicinum</i>), a type of dragonfly, dines on a hapless insect.
        `,
        time: "2025-06-08T14:09:21",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/14",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "cougar_damselfly_20240816": {
        location: "Cougar Mountain Regional Wildland Park",
        title: "blue damsel",
        description: `
            Spreadwing damselfly (family <i>lestidae</i>).
        `,
        time: "2024-08-16T20:06:31",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 80,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "cougar_mtn_apollo": {
        location: "Cougar Mountain Regional Wildland Park",
        title: "parnassian butterfly",
        description: ``,
        time: "2025-06-28T16:24:42",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "cougar_push_pin_slime_17stack_20260125": {
        location: "Coal Creek Natural Area",
        title: "push pin slime mold",
        description: ``,
        time: "2026-01-25T12:52:34",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 80,
        exposure: "1.5 sec",
        stack: 17,
        teleconverter: false,
        flash: false,
    },

    "echo_peak_brutal_ant": {
        location: "Echo Peak",
        title: "brutal ant",
        description: `
        `,
        time: "2024-04-20T12:07:45",
        lens: "Laowa 85mm f/5.6 2x Ultra Macro APO",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 160,
        exposure: "1/200 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "grayson_highlands_massie_gap_ponies_20250825": {
        location: "Grayson Highlands, VA",
        title: "massie gap ponies",
        description: ``,
        time: "2025-08-25T12:55:23",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/9",
        iso: 320,
        exposure: "1/400 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "honey_dew_creek_hoverfly_king": {
        location: "Honey Dew Creek",
        title: "hoverfly king",
        description: `
        `,
        time: "2024-07-07T11:52:42",
        lens: "Laowa 85mm f/5.6 2x Ultra Macro APO",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "kirkjufell_foss": {
        location: "Grundarfjörður, Ísland",
        title: "kirkjufellfoss",
        description: `
            Long exposure of the iconic Kirkjufell foss on a drizzly gray day.
        `,
        time: "2023-10-03",
        lens: "Voigtländer 35 mm / 1:1.2 Nokton X",
        camera: "Fujifilm X-Pro3",
        aperture: "f/3.2",
        iso: 160,
        exposure: "4 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "kubota_black_tipped_darner_close": {
        location: "Kubota Garden",
        title: "black-tipped darner",
        description: `
            <i>aeshna tuberculifera</i>
        `,
        time: "2025-05-26T17:07:36",
        lens: "Zeiss Apo-Makro-Planar T* 4/120",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 320,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "lincoln_jay_20251020": {
        location: "Lincoln Park",
        title: "stellar's jay",
        description: `
        `,
        time: "2025-10-20T13:26:25",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 1600,
        exposure: "1/80 sec",
        stack: false,
        teleconverter: "1.4x",
        flash: false,
    },

    "nbc_ceranus_blue_20251101": {
        location: "Mission, TX",
        title: "ceranus blue",
        description: ``,
        time: "2025-11-01T15:44:06",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/10",
        iso: 800,
        exposure: "1/160 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "nbc_white-striped_longtail_20251101": {
        location: "Mission, TX",
        title: "white-striped longtail",
        description: ``,
        time: "2025-11-01T15:33:30",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/11",
        iso: 640,
        exposure: "1/320 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "nisqually_heron_fish_toss_20251017": {
        location: "Billy Frank Jr. Nisqually National Wildlife Refuge",
        title: "Heron Fish Toss",
        description: `
        `,
        time: "2025-10-17T15:39:55",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 640,
        exposure: "1/1000 sec",
        stack: false,
        teleconverter: "1.4x",
        flash: false,
    },

    "nisqually_yellowlegs_ripples": {
        location: "Billy Frank Jr. Nisqually National Wildlife Refuge",
        title: "yellowleg ripples",
        description: `
        `,
        time: "2024-11-29T11:29:32",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/5.6",
        iso: 800,
        exposure: "1/350 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "pratt_common_coral_slime_20260526": {
        location: "Pratt Balcony",
        title: "common coral slime mold",
        description: ``,
        time: "2026-05-26T11:47:16",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 500,
        exposure: "1/125 sec",
        stack: 40,
        teleconverter: false,
        flash: true,
    },

    "pratt_honeycomb_coral_slime_20260526": {
        location: "Pratt Balcony",
        title: "honeycomb coral slime mold",
        description: ``,
        time: "2026-05-26T13:01:41",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 500,
        exposure: "1/125 sec",
        stack: 19,
        teleconverter: false,
        flash: true,
    },

    "reecer_metalmark_20250913": {
        location: "Reecer Creek",
        title: "mormon metalmark",
        description: ``,
        time: "2025-09-13T15:33:53",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/9",
        iso: 640,
        exposure: "1/640 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "rocky_ford_large_marble_20260602": {
        location: "Rocky Ford",
        title: "large marble",
        description: ``,
        time: "2026-06-02T15:11:29",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 320,
        exposure: "1/800 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "rocky_ford_red_admiral_20260602": {
        location: "Rocky Ford",
        title: "red admiral",
        description: ``,
        time: "2026-06-02T10:44:33",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 100,
        exposure: "1/400 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "seward_crow_angel": {
        location: "Seward Park",
        title: "crow angel",
        description: `
        `,
        time: "2024-12-26T15:48:20",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 800,
        exposure: "1/1000 sec",
        stack: false,
        teleconverter: "1.4x",
        flash: false,
    },

    "seward_crow_profile": {
        location: "Seward Park",
        title: "crow eye reflecting tahoma",
        description: `
        `,
        time: "2024-12-07T16:37:18",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/5.6",
        iso: 1600,
        exposure: "1/500 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "seward_hemitrichia_bouquet_20260110": {
        location: "Seward Park",
        title: "hemitrichia bouquet",
        description: `hemitrichia slime mold`,
        time: "2026-01-10T12:24:32",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 80,
        exposure: "1/125 sec",
        stack: 27,
        teleconverter: false,
        flash: true,
    },

    "seward_push_pin_slime_mold_20251213": {
        location: "Seward Park",
        title: "push pin slime mold",
        description: ``,
        time: "2025-12-13T15:45:27",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 500,
        exposure: "1/125 sec",
        stack: 24,
        teleconverter: false,
        flash: true,
    },

    "skagit_dowitcher_sparkle": {
        location: "Skagit Wildlife Area - Leque Island Unit",
        title: "sparkle dowitcher",
        description: `
        `,
        time: "2024-12-24T13:10:55",
        lens: "Fujifilm GF 500mm f/5.6 R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/8",
        iso: 80,
        exposure: "1/200 sec",
        stack: false,
        teleconverter: "1.4x",
        flash: false,
    },

    "soos_creek_twelve_spot_skimmer": {
        location: "Soos Creek",
        title: "twelve spot skimmer",
        description: ``,
        time: "2025-07-06T09:58:14",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 80,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "south_seattle_arboretum_hoverfly": {
        location: "South Seattle College Arboretum",
        title: "hoverfly",
        description: `
        `,
        time: "2025-05-11T12:52:41",
        lens: "Zeiss Apo-Makro-Planar T* 4/120",
        camera: "Fujifilm GFX100 II",
        aperture: "f/11",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "teanaway_black_tipped_darner_20250719": {
        location: "Bean Creek Basin",
        title: "black-tipped darner",
        description: ``,
        time: "2025-07-19T14:50:59",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 160,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "teanaway_moth_daisy_20250713": {
        location: "Teanaway Community Forest",
        title: "everlasting tebenna moth on daisy",
        description: ``,
        time: "2025-07-13T09:17:11",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/18",
        iso: 80,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "teanaway_western_sheep_moth_20260720": {
        location: "Teanaway - Dickey Creek",
        title: "western sheep moth",
        description: ``,
        time: "2026-07-20T13:31:01",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/9",
        iso: 1000,
        exposure: "1/400 sec",
        stack: false,
        teleconverter: false,
        flash: false,
    },

    "thurber_sprouting_hawthorn_seed_20251227": {
        location: "Cougar Mountain Regional Wildland Park",
        title: "sprouting hawthorn seed",
        description: ``,
        time: "2025-12-27T13:30:34",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 80,
        exposure: "1/125 sec",
        stack: 24,
        teleconverter: false,
        flash: true,
    },

    "tiger_coral_slime_closeup_20260412": {
        location: "Lake Tradition",
        title: "common coral slime mold",
        description: ``,
        time: "2026-04-12T13:05:20",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 200,
        exposure: "1/125 sec",
        stack: 24,
        teleconverter: false,
        flash: true,
    },

    "tiger_moth_20260624": {
        location: "Tiger Mountain",
        title: "tiger moth",
        description: ``,
        time: "2026-06-24T12:16:43",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 200,
        exposure: "1/125 sec",
        stack: 17,
        teleconverter: false,
        flash: true,
    },

    "tiger_mountain_green_lacewing": {
        location: "Tiger Mountain",
        title: "green lacewing",
        description: `
        `,
        time: "2024-10-13T12:57:01",
        lens: "Fujifilm GF 120mm f/4 Macro R LM OIS WR",
        camera: "Fujifilm GFX100 II",
        aperture: "f/13",
        iso: 320,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "tiger_mtn_tiger_lily": {
        location: "Tiger Mountain West #3",
        title: "tiger lily",
        description: `
        `,
        time: "2025-07-03T13:22:54",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/14",
        iso: 200,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },

    "tiger_push_pin_slime_20260117": {
        location: "Lake Tradition",
        title: "push pin slime mold",
        description: ``,
        time: "2026-01-17T13:36:25",
        lens: "Laowa 25mm f/2.8 2.5-5X Ultra Macro",
        camera: "Fujifilm GFX100 II",
        aperture: "f/4",
        iso: 80,
        exposure: "1/125 sec",
        stack: 18,
        teleconverter: false,
        flash: true,
    },

    "yard_katydid_nymph": {
        location: "Columbia City",
        title: "katydid nymph",
        description: `
        `,
        time: "2025-06-12T20:37:33",
        lens: "Nikon AF Micro-Nikkor 200mm f/4D",
        camera: "Fujifilm GFX100 II",
        aperture: "f/16",
        iso: 80,
        exposure: "1/125 sec",
        stack: false,
        teleconverter: false,
        flash: true,
    },


}
